print("Manejo de informacion de entrada con python")
print("-----------------------------------------")
primer_nombre = input("ingrese su primer nombre")
primer_apellido = input("ingrese su primer apellido")
color_favorito = input("ingrese su color favorito")
comida_favorita = input("ingrese su comida favorita")
print("Hola", primer_nombre, primer_apellido, "es un gusto saludarte")
print("a mi tambien me gusta la", comida_favorita, "pero mi color favorito es el", color_favorito)